### ISSUE TITLE
Can we link to these other repositories?

### ISSUE THREAD

**Issue by AndreaThorn** [ecacomsig/Mieres-2018#4]
These are from earlier meetings:
https://github.com/ritagior/R-tutorial-ECACOMSIG-Freudenstadt
https://github.com/keitaroyam/ECACOMSIG-ECM30
https://github.com/JonnyCBB/ECACOMSIG-ComputingSchool2015
https://github.com/vincefn/CrystCompSchool
https://github.com/luc-j-bourhis/rovinj-2015-numopt-tut
https://github.com/luc-j-bourhis/rovinj-2015-cctbx-tutorial
https://github.com/karine-sparta/eca-sig9-rovinj-gui

**Comment by fsimkovic** [comment]
Added a [new repository for Rovinj](https://github.com/ecacomsig/Rovinj-2015).

**Comment by fsimkovic** [comment]
@AndreaThorn you can edit the README files also online, so probably easiest to add to the files directly.
